# Generated by Django 2.2.7 on 2019-12-02 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='int_list',
            field=models.CharField(default='0', max_length=100, validators=[django.core.validators.int_list_validator]),
        ),
    ]
