# Generated by Django 2.2.7 on 2019-12-03 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_puzzle_int_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='int_list',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='player',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_1',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
