# Generated by Django 2.2.7 on 2019-12-03 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191203_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='box_1_value_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
    ]
