# Generated by Django 2.2.7 on 2019-12-03 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191203_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_3',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_7',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_1_value_9',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_2',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_6',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_7',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_2_value_9',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_1',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_5',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_6',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_7',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_3_value_9',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_1',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_3',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_5',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_7',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_4_value_9',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_2',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_3',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_7',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_8',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_5_value_9',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_1',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_3',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_5',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_7',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_6_value_9',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_1',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_3',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_4',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_5',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_7',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_7_value_9',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_1',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_3',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_4',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_7',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_8',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_8_value_9',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_2',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_3',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_4',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_7',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_8',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='box_9_value_9',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
    ]
