# Generated by Django 2.2.7 on 2019-12-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_puzzle_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='account',
        ),
    ]
